repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/add-trailing-comma
    rev: "v3.1.0"
    hooks:
      - id: add-trailing-comma
        args: ["--py36-plus"]
  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: ["--ignore=E203,E221,E226,E241,E251,E731"]
        # Exceptions that were made to make the the manual conversion from
        # non-compliance with flake8 to compliance easier. Can possibly be
        # abandoned eventually.
        # E203  Whitespace before ':'
        # E221  Multiple spaces before operator
        # E226  Missing whitespace around arithmetic operator
        # E241  Multiple spaces after ','
        # E251  Unexpected spaces around keyword / parameter equals
        # E731  Do not assign a lambda expression, use a def
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.0"
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
